[workspace]
members = [
    "masu","games/osero","games/picross","games/syogi","common","games/gomoku_narabe","games/picross"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

